### ISSUE TITLE
Room

### ISSUE THREAD

**Issue by Moxi3231** [Aatish13/ArGame#1]
![Room](https://user-images.githubusercontent.com/42675676/76992044-9ed16c80-6970-11ea-80d8-4849c5a83879.jpeg)
![Map](https://user-images.githubusercontent.com/42675676/76992060-a3962080-6970-11ea-92ad-2e628f5ec4ca.jpeg)
![Anchor](https://user-images.githubusercontent.com/42675676/76992066-a729a780-6970-11ea-8f6f-21e11e31be09.jpeg)

**Comment by Moxank6277** [comment]
![Anchor](https://user-images.githubusercontent.com/42675676/76991986-85c8bb80-6970-11ea-8890-5f91ba06dd4c.jpeg)
![Map](https://user-images.githubusercontent.com/42675676/76991991-882b1580-6970-11ea-80c2-ce9ec3c297a2.jpeg)
